[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.greenlet", "postgresql", "gcc", "glibc", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[phases.build]
cmds = ["cd backend && python -c 'print(\"Build completed\")'"]

[start]
cmd = "cd backend && python main.py"

[variables]
PYTHONPATH = "/app:/app/backend"
LD_LIBRARY_PATH = "/nix/store/*/lib"